services:
  postgresql:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/schema_Postgres.sql:/docker-entrypoint-initdb.d/schema_Postgres.sql
    networks:
      - db_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb/schema_MySQL.sql:/docker-entrypoint-initdb.d/schema_MySQL.sql
    networks:
      - db_net

  sqlite:
    image: keinos/sqlite3:latest
    container_name: sqlite
    restart: unless-stopped
    user: root
    environment:
      SQLITE_USER: admin
      SQLITE_DATABASE: test
    volumes:
      - ./sqlite_data:/var/lib/sqlite
      - ./initdb/schema_SQLite.sql:/docker-entrypoint-initdb.d/schema_SQLite.sql
    command: >
      sh -c "sqlite3 /var/lib/sqlite/test.db < /docker-entrypoint-initdb.d/schema_SQLite.sql && tail -f /dev/null"
    networks:
      - db_net

volumes:
  postgres_data: { }
  mysql_data: { }

networks:
  db_net:
    driver: bridge
